title: Angel's Project Website
description: This is the Angel's project website for COMS3007

url: https://leyicui-angel.github.io/website-LeyiCui-Angel/

aux_links: # remove if you don't want this link to appear on your pages
  Template Repository: https://github.com/LeyiCui-Angel/website-LeyiCui-Angel

permalink: pretty

# Remote Setting
baseurl: "/guidelines"
# url: ""

# Theme
# theme: "just-the-docs"
remote_theme: pmarsceill/just-the-docs
